model:
  batch_size: 128
  coord_descent: true
  coord_descent_model_lr: 1.00e-04
  coord_descent_model_n_epochs: 4
  coord_descent_sindy_attention_lr: 1.00e-02
  coord_descent_sindy_attention_n_epochs: 2
  dataset: sst
  decoder: mlp
  decoder_depth: 1
  device: cpu
  dropout: 0.1
  early_stop: 0
  encoder: sindy_attention_transformer
  encoder_depth: 1
  epochs: 2
  forecast_length: 1
  generate_test_plots: false
  generate_training_plots: false
  hidden_size: 20
  identifier: sst_test_sa
  input_length: 10
  n_trials: 3
  n_heads: 4
  n_sensors: 5
  n_well_tracks: 10
  name: SA
  poly_order: 1
  save_every_n_epochs: 10
  seed: 0
  sindy_attention_threshold: 0.05
  sindy_attention_threshold_n_epochs: 10
  sindy_attention_weight: 10
  skip_load_checkpoint: true
  verbose: true

hyperparameters:
  coord_descent_model_lr:
    lower_bound: 1.0e-05
    type: loguniform
    upper_bound: 0.01
  coord_descent_sindy_attention_lr:
    lower_bound: 1.0e-05
    type: loguniform
    upper_bound: 0.01
  coord_descent_model_n_epochs:
    lower_bound: 1
    type: randint
    upper_bound: 4
  coord_descent_sindy_attention_n_epochs:
    lower_bound: 1
    type: randint
    upper_bound: 4
