hyperparameters:
  dropout:
    choices:
    - 0.0
    - 0.1
    type: choice
  encoder_depth:
    choices:
    - 1
    - 2
    - 3
    type: choice
  lr:
    lower_bound: 0.0001
    type: loguniform
    upper_bound: 0.1
  sindy_attention_weight:
    lower_bound: 1.0
    type: loguniform
    upper_bound: 10.0
  sindy_loss_weight:
    lower_bound: 1.0
    type: loguniform
    upper_bound: 10.0
model:
  batch_size: 128
  coord_descent: false
  dataset: sst
  decoder: mlp
  decoder_depth: 1
  delete_checkpoint: true
  device: cuda:0
  dt: 1.0
  early_stop: 10
  encoder: sindy_loss_gru
  epochs: 100
  forecast_length: 1
  generate_loss_plots: false
  generate_test_plots: false
  generate_training_plots: false
  hidden_size: 20
  identifier: sst_sindy_loss_gru_mlp_0
  input_length: 10
  n_heads: 4
  n_sensors: 5
  n_trials: 100
  n_well_tracks: 10
  poly_order: 1
  save_every_n_epochs: 10
  seed: 0
  sindy_attention_threshold: 0.1
  sindy_attention_threshold_n_epochs: 10
  sindy_loss_threshold: 0.1
  skip_load_checkpoint: true
  verbose: false
