model:
  batch_size: 128
  coord_descent: false
  dataset: sst
  decoder: mlp
  decoder_depth: 2
  delete_checkpoint: false
  device: cuda:0
  dropout: 0.0020844220078642534
  dt: 1.0
  early_stop: 10
  encoder: sindy_loss_moe_gru
  encoder_depth: 2
  epochs: 50
  forecast_length: 20
  generate_loss_plots: false
  generate_test_plots: false
  generate_training_plots: false
  hidden_size: 40
  identifier: sst_sindy_loss_moe_gru_20_mlp_4
  input_length: 20
  lr: 0.005999910038206999
  n_experts: 50
  n_heads: 4
  n_sensors: 10
  n_well_tracks: 10
  poly_order: 1
  save_every_n_epochs: 10
  seed: 4
  sindy_layer_threshold: 0.01
  sindy_layer_threshold_n_epochs: 10
  sindy_layer_weight: 0.05767133749383411
  sindy_loss_threshold: 0.01
  sindy_loss_weight: 0.20400685646580605
  skip_load_checkpoint: true
  std_init_max: 2.0
  std_init_min: 0.1
  strict_symmetry: true
  verbose: true
