model:
  batch_size: 128
  coord_descent: true
  coord_descent_model_lr: 0.001
  coord_descent_model_n_epochs: 5
  coord_descent_sindy_attention_lr: 0.1
  coord_descent_sindy_attention_n_epochs: 2
  dataset: plasma
  decoder: cnn
  decoder_depth: 1
  device: cuda:0
  delete_checkpoint: false
  dropout: 0.1
  early_stop: 0
  encoder: sindy_attention_transformer_rollout
  encoder_depth: 1
  epochs: 10
  forecast_length: 5
  generate_loss_plots: true
  generate_test_plots: true
  generate_training_plots: true
  hidden_size: 20
  identifier: SAR-T
  input_length: 20
  n_heads: 4
  n_sensors: 5
  n_trials: 50
  n_well_tracks: 10
  poly_order: 1
  save_every_n_epochs: 1
  seed: 0
  sindy_attention_threshold: 0.05
  sindy_attention_threshold_n_epochs: 10
  sindy_attention_weight: 0.0
  skip_load_checkpoint: true
  verbose: true
