model:
  batch_size: 128
  best_checkpoint_path: /home/alexey/Git/T-SHRED/checkpoints/77f09_00001_best.pt
  config: /home/alexey/Git/T-SHRED/results/planetswe_sindy_loss_lstm_cnn_0/hp_config_77f09_00001.yaml
  coord_descent: false
  d_data_in: 3
  d_data_out: 3
  d_model: 15
  data_cols_in: 512
  data_cols_out: 512
  data_rows_in: 256
  data_rows_out: 256
  dataset: planetswe
  decoder: cnn
  decoder_depth: 1
  delete_checkpoint: true
  device: cuda:0
  dim_feedforward: 80
  dropout: 0.0
  dt: 1.0
  early_stop: 10
  encoder: sindy_loss_lstm
  encoder_depth: 2
  epochs: 100
  forecast_length: 1
  generate_loss_plots: false
  generate_test_plots: false
  generate_training_plots: false
  hidden_size: 20
  identifier: 77f09_00001
  input_length: 10
  latest_checkpoint_path: /home/alexey/Git/T-SHRED/checkpoints/77f09_00001_latest.pt
  lr: 0.002533633283868942
  n_heads: 4
  n_sensors: 5
  n_trials: 100
  n_well_tracks: 10
  output_size: 393216
  poly_order: 1
  save_every_n_epochs: 10
  seed: 0
  sindy_attention_threshold: 0.1
  sindy_attention_threshold_n_epochs: 10
  sindy_attention_weight: 7.323249740319171
  sindy_loss_threshold: 0.1
  sindy_loss_weight: 4.583870721726095
  skip_load_checkpoint: true
  verbose: false