model:
  batch_size: 128
  coord_descent: true
  dataset: sst
  decoder: mlp
  decoder_depth: 1
  device: cuda:0
  dropout: 0.1
  delete_checkpoint: true
  early_stop: 10
  encoder: sindy_attention_transformer_rollout
  encoder_depth: 1
  epochs: 50
  forecast_length: 5
  generate_test_plots: false
  generate_training_plots: false
  hidden_size: 20
  identifier: sst_test_sar
  input_length: 10
  n_trials: 50
  n_heads: 4
  n_sensors: 5
  n_well_tracks: 10
  name: SAR
  poly_order: 1
  save_every_n_epochs: 10
  seed: 0
  sindy_attention_threshold_n_epochs: 10
  sindy_attention_threshold: 0.05
  skip_load_checkpoint: true
  verbose: true

hyperparameters:
  coord_descent_model_lr:
    lower_bound: 1.0e-05
    type: loguniform
    upper_bound: 1.0e-02
  coord_descent_sindy_attention_lr:
    lower_bound: 1.0e-05
    type: loguniform
    upper_bound: 1.0e-02
  sindy_attention_weight:
    lower_bound: 1.0
    type: loguniform
    upper_bound: 10.0
  coord_descent_model_n_epochs:
    lower_bound: 1
    type: randint
    upper_bound: 10
  coord_descent_sindy_attention_n_epochs:
    lower_bound: 1
    type: randint
    upper_bound: 10
