model:
  batch_size: 128
  coord_descent: true
  coord_descent_model_lr: 0.0001
  coord_descent_model_n_epochs: 1
  coord_descent_sindy_attention_lr: 0.0001
  coord_descent_sindy_attention_n_epochs: 1
  dataset: sst
  decoder: cnn
  decoder_depth: 1
  delete_checkpoint: true
  device: cuda:0
  dropout: 0.1
  dt: 1.0
  early_stop: 10
  encoder: sindy_attention_transformer
  encoder_depth: 4
  epochs: 10
  forecast_length: 5
  generate_loss_plots: false
  generate_test_plots: false
  generate_training_plots: false
  hidden_size: 20
  identifier: sst_sindy_attention_transformer_5_cnn_0
  input_length: 10
  n_heads: 1
  n_sensors: 5
  n_trials: 25
  n_well_tracks: 10
  poly_order: 1
  save_every_n_epochs: 10
  seed: 0
  sindy_attention_threshold: 0.1
  sindy_attention_threshold_n_epochs: 10
  sindy_attention_weight: 1.0
  sindy_loss_threshold: 0.1
  sindy_loss_weight: 1.0
  skip_load_checkpoint: true
  verbose: True
